language: php

php:
  - 5.3
  - 5.4

before_script:
  - composer self-update
  - composer install --dev

script:
  - phpunit
  - composer require --dev --prefer-dist silverstripe/framework:~3.0
  - phpunit